apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hugo-test-project-poi-backend-app-dev
  annotations:
    argocd/app-name: hugo-test-project-poi-backend-app-dev
    backstage.io/kubernetes-id: hugo-test-project-poi-backend-app
    backstage.io/kubernetes-namespace: hugo-test-project
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/hugo-test-project-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/hugo-test-project/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/hugo-test-project/deployments/hugo-test-project-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/hugo-test-project-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:hdmeyer"
  system: workshop-system-hugo-test-project
  providesApis:
    - backend-api-hugo-test-project
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hugo-test-project
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:hdmeyer"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-hugo-test-project
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: https://hugo-test-project-poi-backend-app-hugo-test-project.apps.kovj5vhc.eastus.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-aro24/hugo-test-project-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:hdmeyer"
  system: workshop-system-hugo-test-project
  definition:
    $text: https://github.com/rhdh-aro24/hugo-test-project-backend/tree/main/src/main/resources/META-INF/openapi.yaml
